export const history = [
  {
    date: "Apr 3, 2026",
    role: "Software Engineer",
    type: "technical",
    score: 88,
    duration: "42 min",
    questions: 5,
  },
  {
    date: "Apr 2, 2026",
    role: "Product Manager",
    type: "behavioral",
    score: 74,
    duration: "35 min",
    questions: 4,
  },
  {
    date: "Mar 31, 2026",
    role: "Software Engineer",
    type: "behavioral",
    score: 79,
    duration: "28 min",
    questions: 4,
  },
  {
    date: "Mar 29, 2026",
    role: "Data Scientist",
    type: "case-study",
    score: 91,
    duration: "50 min",
    questions: 6,
  },
  {
    date: "Mar 27, 2026",
    role: "Product Manager",
    type: "technical",
    score: 66,
    duration: "38 min",
    questions: 5,
  },
  {
    date: "Mar 25, 2026",
    role: "Software Engineer",
    type: "behavioral",
    score: 72,
    duration: "31 min",
    questions: 4,
  },
];